title: oratot.com
description: "Personal website of Paride, an Italian guy who likes video games. Hosting pre-existing JavaScript utilities and more cool stuff!"
url: "https://www.oratot.com"
tagline: "Personal website of Paride, hosting pre-existing JavaScript utilities and more cool stuff."

author:
  name: Paride Totaro
  url: "https://www.oratot.com"

social:
  name: Oratot
  links:
    - https://www.youtube.com/@ItzOratotITA
    - https://www.reddit.com/user/Which-Taro5092/
    - https://www.twitch.tv/oratot
    - https://github.com/itzoratotita
    - https://www.oratot.com/discord

logo: /assets/blueprint_logo.png

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    formatter: HTML

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .github
  - README.md
  - LICENSE
  - .gitignore
  - CNAME
